#!/bin/sh
### BEGIN INIT INFO
# Provides:          sensorhub
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Enables /usr/bin/sensorhub
### END INIT INFO

. /lib/lsb/init-functions
SENSORHUBPID=`ps -efa | grep "/usr/bin/sensorhubd" | grep -v grep | cut -c 9-15`

case "$1" in
  start)
    echo -n "[....] Starting sensorhub "
    if [ -z "$SENSORHUBPID" ]; then 
      /usr/bin/sensorhubd&
      log_end_msg $?
    else
      echo -n "... already running with PID $SENSORHUBPID"
      log_end_msg 1
    fi
    ;;
  stop)
    echo -n "[....] Stopping sensorhub ..."
    if [ "$SENSORHUBPID" ]; then 
      kill $SENSORHUBPID
      echo -n "Sensorhubd: " >> /var/log/sensorhubd.log
      date >> /var/log/sensorhubd.log
      echo "Stopping sensorhubd via service sensorhub stop" >> /var/log/sensorhubd.log
      log_end_msg $?
    else
      echo -n "not running ..."
      log_end_msg 1
    fi
    ;;
  clearlog)
    echo -n "[....] Stopping sensorhub ..."
    if [ "$SENSORHUBPID" ]; then
      kill $SENSORHUBPID
      date >> /var/log/sensorhubd.log
      echo "Stopping sensorhubd via service sensorhub stop" >> /var/log/sensorhubd.log
      log_end_msg $?
    else
      echo -n "not running ..."
      log_end_msg 1
    fi
    echo "Delete logfile: /var/log/sensorhubd.log"
    rm /var/log/sensorhubd.log
    echo -n "[....] Starting sensorhub "
    SENSORHUBPID=`ps -efa | grep "/usr/bin/sensorhubd" | grep -v grep | cut -c 9-15`
    if [ -z "$SENSORHUBPID" ]; then
      /usr/bin/sensorhubd&
      log_end_msg $?
    else
      echo -n "... already running with PID $SENSORHUBPID"
      log_end_msg 1
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/sensorhub {start|stop|clearlog}"
    exit 1
    ;;
esac

exit 0
